defaults:
  - base_trainer

_target_: torchtts.trainers.codec_yc_trainer.CodecTrainer

use_cudnn_benchmark: False

save_interval: 1000
max_steps: 3000000

# loss weight
lambda:
  lambda_feat_match_loss: 2.0
  lambda_mel_loss: 10.0
  lambda_adv: 2.0
  lambda_disc: 1.0
  lambda_stft_loss: 1.0

# Discriminator training
disc_train_start_steps: 50000

# Optimizers
gen_optim_params:
  lr: 1.0
  betas: [0.5, 0.9]
disc_optim_params:
  lr: 1.0
  betas: [0.5, 0.9]

# Schedules
gen_schedule_params:
  warmup_step: 10000
  start_step: 1000000
  decay_step: 500000
  gamma: 0.5
  min_lr: 1.0e-4 # this should be the final lr
  max_lr: 2.0e-4 
disc_schedule_params:
  warmup_step: 10000
  start_step: 1000000
  decay_step: 500000
  gamma: 0.5
  min_lr: 1.0e-4 # this should be the final lr
  max_lr: 2.0e-4 

# Multi-resolution stft loss
use_stft_loss: false
stft_loss_steps: 3000000
stft_loss_params:
  fft_sizes: [ 128, 256, 512, 1024, 2048 ]
  hop_sizes: [ 32, 64, 128, 256, 512 ]
  win_lengths: [ 128, 256, 512, 1024, 2048 ]
  window: hann_window
# Multi-resolution mel loss
use_mel_loss: true
mel_loss_params:
  sample_rate: 16000
# Feature matching loss
use_feat_match_loss: true

# Disaggrement loss
use_disagreement_loss: false

# Moving average
ema_decay: 0.9999
ema_update_interval: 1
ema_reset_interval: 500000